### ISSUE TITLE
Provide a high-level SRT interface for video transport

### ISSUE THREAD

**Issue by birme** [Eyevinn/swift-srt#2]
Currently we only provide bindings for libsrt (wrappers) and the purpose of this ticket is to provide a high-level SRT interface for easier integrating with video related transports.

Pseudo-code example:
```
let serverUrl = URL(string: "srt://<ip>:<port>")
let stream = SRTStream(serverUrl)
let tsWriter = TSWriter()
tsWriter.delegate = stream // TSWriterDelegate
```

The SRTStream class will extend and implement the below protocol
```
public protocol TSWriterDelegate: class {
    func didOutput(_ data: Data)
}
```

An example of a TSWriter is available here: https://github.com/shogo4405/HaishinKit.swift/blob/master/Sources/TS/TSWriter.swift

**Comment by birme** [comment]
@jesperlundqvist: Publish a new minor version with this feature included and we can close this ticket. Thanks!

**Comment by birme** [comment]
Cocapods seems to be up and running again so should be possible to make a release @jesperlundqvist 
Then we can close this one.

**Comment by pjvds** [comment]
@birme you closed this issue by marking it completed, but from what I can see this is not added to swift-srt yet, correct?

**Comment by birme** [comment]
I thought it was, but we might missed adding it to the documentation. Can @sinewave440hz have a look?

https://github.com/Eyevinn/swift-srt/blob/main/swift-srt/Stream.swift

**Comment by sinewave440hz** [comment]
Yes this is merged since some time back. What may not have been obvious is that the feature was named [Feature/video transport interface](#5). I have linked the issue now for clarity. [This is the merge commit](https://github.com/Eyevinn/swift-srt/commit/49fded4dc712f8fe7fefb1a559b95662fc5f9431). Do let me know how you get on :)

**Comment by pjvds** [comment]
Thanks for the clarification and for the great library!
